### PR TITLE
Fixed long loading state after tx is submitted

### LINKED ISSUE #75: Long loading state when staking | unstaking after transaction was successfully validated.
### Expected behavior

User clicks stake, signs transaction, transaction is sent to blockchain, while it is being mined, user sees the “circle” (see screenshot). once Tx is mined, WebApp reverts back to “ready” status as it was before firing off the tx.

### Actual behavior

WebApp is frozen in the “circle” state, even after tx is mined. hard refresh of webApp gets you out of this state into the “ready state”. Also, waiting forever gets you there too. but it takes way too long, and a lot longer than what it used to. (minutes!). just measured 1.5min now. also seen more.

### PR DESCRIPTION
**Pull request by soloseng**
### Description

No longer waiting for backend to complete transactions before updating the app state after a transaction was submitted.

### Related issues

- Fixes #75

### CODE REVIEW

File: src/features/swap/hooks/useUnstaking.ts [hunk 1]
```diff
@@ -39,7 +39,7 @@ export function useUnstaking() {
       status: 'signed_transaction',
       value: stCeloAmount.displayAsBase(),
     });
-    await api.withdraw(address);
+    api.withdraw(address);
```
Comment (pahor167) [inline src/features/swap/hooks/useUnstaking.ts:42]: Are we sure we want to remove await also on withdraw ? 

Once this is done user will not know whether withdrawal succeeded. 

(For activation it doesn't matter that much since we are running it once a day automatically and it is not that vital)

Comment (soloseng) [reply src/features/swap/hooks/useUnstaking.ts:42]: This should be fine to do here, as this hook never does anything with the HTTP response. Any failed withdrawal would be handled by `useWithdrawalBot` in `AccountContext.tsx` whenever a page is loaded.

Comment (soloseng) [reply src/features/swap/hooks/useUnstaking.ts:42]: Just double checked the error handling (for both `withdraw` and `activate`) by forcing a 500 response from the backend. No errors were shown in the front end when that happens.

Front-end works as expected

Comment (pahor167) [reply src/features/swap/hooks/useUnstaking.ts:42]: In that case we could consider to add displaying of errors but if we will decide so it should be in separate task

**Review by pahor167 — APPROVED** [review]
