### PR TITLE
Fix/gas estimation

### LINKED ISSUE #200: Investigate stCELO "withdrawal" bug
_Copy/pasting bug report from Daniel on [Slack](https://celo-org.slack.com/archives/C0508EV6N3E/p1705330613535579)_

> I am getting an error when I try to unstake on stCelo. I get a:
> 
> ```
> eth_signTransaction: Gas must be provided to sign a transaction
> ```
> 
> I do have CELO to pay for gas.
> this is a screenshot from the console:
> 
> image
> 
> we reviewed this error with @therealharpaljadeja and concluded it might be a FrontEnd Issue. @therealharpaljadeja also noticed that the contracts are not verified on Celoscan
```[tasklist]
### Tasks
- [ ] Verify stcelo contracts on celoscan.io
- [ ] Reproduce or understand bug
- [ ] Fix bug
```

### PR DESCRIPTION
**Pull request by nicolasbrugneaux**
This PR aims to fix several issues:

- [Closes #200] by estimating gas beforehand, Celo Terminal didn't do it, but other wallets did
- Fixes an unreported bug with the `Max` buttons
- Fixes a visual bug when user would cancel via wallet connect

### CODE REVIEW

**Review by shazarre — APPROVED** [review]

File: src/features/swap/hooks/useStaking.ts [hunk 1]
```diff
@@ -28,6 +28,19 @@ export function useStaking() {
 
   const client = usePublicClient();
 
+  const _estimateGas = useCallback(
```
Comment (aaronmgdr) [inline src/features/swap/hooks/useStaking.ts:31]: because this seems to get passed around and its not a generic estimate gas but estimate for manager contract, maybe add estimateManagerGas ?

Comment (nicolasbrugneaux) [reply src/features/swap/hooks/useStaking.ts]: Done
