### PR TITLE
 fix govern and stake bugs

### LINKED ISSUE #151: User can't vote after switching connected accounts
_Documenting bugs reported by @product-matt on [Slack](https://celo-org.slack.com/archives/C0508EV6N3E/p1690481299575569)_

## User can't vote after switching connected accounts

- [x] Solution in https://github.com/celo-org/staked-celo-web-app/pull/150
- [ ] QA: @product-matt to confirm that bug is fixed for him

## Context

> Observed: Voted with 5.xxx CELO on CGP with one address connected (MM). Disconnected MM (on MM and on DApp). Connected 2nd wallet / new address (valora). Now seeing my votes from the MM address, and cannot vote with newly connected account

image

### PR DESCRIPTION
**Pull request by aaronmgdr**
## GOAL

1. fix "if I vote on one CGP, and then want to vote on a second one - cannot do it, just am shown 0 CELO"
2. fix " vote on a CGP with one wallet and then disconnect, but cant vote on same CGP because old vote is cached"
3. fix "balanace shows as zero if i have voted on a different proposal"
4. fix "you recieve WRONG amount of StCELO"
5. fix "500: could not activeate" which had it seem incorectly like staking failed

Fixes #151

### CODE REVIEW

File: src/features/governance/components/Details.tsx [hunk 1]
```diff
@@ -47,23 +47,23 @@ export const Details = ({ proposal }: Props) => {
...
 
   const onVote = useCallback(async () => {
     if (!currentVote || hasVoted) return;
     setTransactionModalOpen(true);
     await voteProposal(proposal, currentVote, { onSent: () => setTransactionModalOpen(false) });
-    setHasVoted(true);
   }, [currentVote, hasVoted, voteProposal, proposal]);
 
   useEffect(() => {
+    console.info('Checking if user has voted', address, proposal.proposalID);
```
Comment (aaronmgdr) [inline src/features/governance/components/Details.tsx:60]: hack but i added this in so the hook uses address and thus def will run when it changes

File: src/features/governance/hooks/useVote.ts [hunk 2]
```diff
@@ -19,10 +19,9 @@ export const useVote = () => {
   const { address } = useAccount();
   const chainId = useChainId();
   const network = chainIdToChain(chainId);
-
   const getVoteCacheKey = useCallback(
-    (id: string) => {
-      return `${network.name}:voteProposal:${id}`;
+    (id: string, addr: string) => {
+      return `${network.name}:${addr}:voteProposal:${id}`;
```
Comment (aaronmgdr) [inline src/features/governance/hooks/useVote.ts:24]: !important! when caching must be by the address, sadly this WILL break the cache for old votes there is no way around that ce la vi

File: src/pages/governance/[...slug].tsx [hunk 3]
```diff
@@ -35,9 +35,7 @@ export const getServerSideProps: GetServerSideProps<Props> = async ({ query, par
 
   const id = params?.slug;
   const proposalID = Array.isArray(id) ? id[0] : id;
-  const chainId =
-    Number(query.chainId as string) ||
-    (process.env.NODE_ENV === 'production' ? Celo.id : Alfajores.id);
+  const chainId = Number(query.chainId as string) || Celo.id;
```
Comment (aaronmgdr) [inline src/pages/governance/[...slug].tsx:38]: everywhere else we default to Celomainnet not sure why we (I) default to Alfajores only when on Dev mode here.

File: src/features/governance/hooks/useVote.ts (hunk 2 above)
Comment (nicolasbrugneaux) [reply src/features/governance/hooks/useVote.ts:24]: c'est la vie indeed

File: src/features/governance/components/Details.tsx (hunk 1 above)
Comment (nicolasbrugneaux) [reply src/features/governance/components/Details.tsx:60]: 99.9% sure this isn't an issue as `getHasVoted` is `useAsyncCallback` wrapping the result of a `useContractRead` using `address` already. This will provoke `getHasVoted` to change

File: src/features/governance/hooks/useVote.ts [hunk 4]
```diff
@@ -92,27 +93,27 @@ export const useVote = () => {
   );
 
   const getProposalVote = useCallback(
-    (proposalId: string) => {
-      const nodeData = votes[proposalId];
-      const localData = readFromCache(getVoteCacheKey(proposalId));
+    async (proposalId: string, address: string) => {
+      const nodeData = await getVotesForProposal(proposalId);
```
Comment (nicolasbrugneaux) [inline src/features/governance/hooks/useVote.ts:97]: thoughts: since this takes around 3-4 seconds to get the data, either we could optimise more or just prioritise the local node data

**Comment by aaronmgdr** [comment]
This looks good

File: src/features/governance/hooks/useVote.ts (hunk 4 above)
Comment (aaronmgdr) [reply src/features/governance/hooks/useVote.ts:97]: maybe optimistic fetching

**Review by soloseng — APPROVED** [review]
🚀
