### PR TITLE
Feat: vote weight fix and validator group votes adjustments

### LINKED ISSUE #254: check if using best balance while voting on governance
there are several balanaces. stcelo, locked, lockedInVoting, etc. 

we should confirm that the one passed in while voting on governance proposals is in fact the best / right one to use.

### LINKED ISSUE #256: Allow some users to change validator despite voting on a proposal
### Component

Select Validator

### Describe the feature you would like

https://clabsco.slack.com/archives/C014SRL4URY/p1721240343891759

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nicolasbrugneaux**
### Description

- Fixes the logic to evaluate `voteWeight` 
- Permits select users to vote despite having a positive lockedVoteBalance
  - List of users can be found here: https://dune.com/queries/3923234/6595515

 [Fix #254]
 [Fix #256]

### CODE REVIEW

File: src/features/governance/hooks/useVote.ts [hunk 1]
```diff
@@ -73,13 +87,12 @@ export const useVote = () => {
       if (proposal.stage !== ProposalStage.Referendum) {
         throw new Error('vote called on proposal that is not in Referendum stage');
       }
-      if (!voteWeight || voteWeight - MAX_AMOUNT_THRESHOLD <= 0) {
-        showErrorToast(
-          'Insufficient balance when taking in account gas costs. Do you have unlockable stCelo?'
```
Comment (aaronmgdr) [inline src/features/governance/hooks/useVote.ts:78]: removing because gas isnt paid in st celo right?

Comment (nicolasbrugneaux) [reply src/features/governance/hooks/useVote.ts:78]: correct

**Review by aaronmgdr — APPROVED** [review]
